title: Sobhan-SRZA (Mr.Sinre)
description: I am an ESFJ-A personality type. I hate proud and lying people and I hate this behavior myself. I am not very warm and cold person, but I communicate with everyone just like normal people.
theme: dark-poole
favicon_ico: "https://avatars.githubusercontent.com/u/90289153?v=4"
color_scheme: dark
