title: "Sobhan-SRZA (Mr.Sinre)"
description: "I'm a problem-solver developer focused on building real-world, production-ready systems."
favicon_ico: "https://avatars.githubusercontent.com/u/90289153?v=4"
color_scheme: "dark"
